version: '3.8'

services:
  frontend:
    image: node:16-alpine
    container_name: rps_front
    working_dir: /app
    volumes: 
      - ./frontend:/app
    stdin_open: true
    tty: true
    command: sh
    ports: 
      - 3005:3005
    restart: on-failure
    environment:
      - NEXT_PUBLIC_HOST=backend
    depends_on:
      - backend

  backend:
    image: node:16-alpine
    container_name: rps_back
    working_dir: /app
    volumes:
      - ./backend:/app
    stdin_open: true
    tty: true
    command: sh
    ports:
      - 3006:3006
    restart: on-failure
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=db
      - MYSQL_PORT=33060
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: rps_db
    volumes:
      - ./database:/var/lib/mysql # persistent data
    ports:
      - 33060:3306
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DEFAULT_AUTH=mysql_native_password